### ISSUE TITLE
GlideLoader doesnt work.

### ISSUE THREAD

**Issue by kundank191** [TangoAgency/avatar-view#32]
Log Cat
```
07-31 23:18:33.132 7905-7905/com.example.kunda.test_avatar_library_withusername E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kunda.test_avatar_library_withusername, PID: 7905
    java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.example.kunda.test_avatar_library_withusername-2/base.apk)
        at agency.tango.android.avatarviewglide.GlideLoader.loadImage(GlideLoader.java:25)
        at agency.tango.android.avatarview.ImageLoaderBase.loadImage(ImageLoaderBase.java:21)
        at com.example.kunda.test_avatar_library_withusername.MainActivity.onCreate(MainActivity.java:19)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

cause of error 
```
public class GlideLoader extends ImageLoaderBase {

    public GlideLoader() {
        super();
    }

    public GlideLoader(String defaultPlaceholderString) {
        super(defaultPlaceholderString);
    }

    @Override
    public void loadImage(@NonNull AvatarView avatarView, @NonNull AvatarPlaceholder avatarPlaceholder, @NonNull String avatarUrl) {
        Glide.with(avatarView.getContext())
                .load(avatarUrl)
                .crossFade() ------>>>here is the error , this method is no longer supported
                .placeholder(avatarPlaceholder)
                .fitCenter()
                .into(avatarView);
    }

}
```

Main Activity 
```
package com.example.kunda.test_avatar_library_withusername;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import agency.tango.android.avatarview.IImageLoader;
import agency.tango.android.avatarview.views.AvatarView;
import agency.tango.android.avatarviewglide.GlideLoader;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        AvatarView imageView = (AvatarView) findViewById(R.id.iv_profile_image);
        IImageLoader imageLoader = new GlideLoader();
        imageLoader.loadImage(imageView,"hhtp:bogusUrl","Kundan");

    }
}
```
Layout File
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:background="#000000"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <agency.tango.android.avatarview.views.AvatarView
        android:id="@+id/iv_profile_image"
        android:layout_width="100dp"
        android:layout_height="100dp"
        app:av_border_color="@android:color/white"
        app:av_border_width="4dp"
        app:av_text_size_percentage="35" />

</android.support.constraint.ConstraintLayout>
```

**Comment by ssucino** [comment]
Any different way than override GlideLoader or using Picasso to fix this out?

**Comment by kundank191** [comment]
Picasso works fine, glide has actually changed its methods that's why glide method should be changed. I don't think there is any other way if one wants to use glide.
just removing that crossFade() method will fix this error.

**Comment by adolfdsilva** [comment]
Same problem +1

**Comment by harsh-illuminz** [comment]
Hello guys this is perfect solution
  

Glide.with(this)
            .load("")
            .apply(RequestOptions().placeholder(AvatarPlaceholder(itemData.addressName?:""))
                .error(AvatarPlaceholder(itemData.addressName?:"")))
            .into(ivUser)
